# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
matrix:
  include:
  - os: linux
    env: BADGE=linux
  - os: osx
    env: BADGE=osx
    env: LD_LIBRARY_PATH=" /opt/local/lib:$LD_LIBRARY_PATH"
    env: CPATH="/opt/local/include:$CPATH"


addons:
  apt:
    packages:
      - ccache
      - libgdal1-dev
      - libproj-dev
      - libhdf5-serial-dev
      - libgeotiff-dev
      - libgsl-dev
      - libudunits2-dev
      - libglu1-mesa-dev
      - freeglut3-dev

  homebrew:
    packages:
      - ccache
      - geos
      - gdal
      - libgeotiff
      - gsl
      - hdf5
      - ldunits

# Code coverage
r_packages:
  - raster
  
language: R
sudo: false
cache: 
  - ccache
  - packages  

before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars

script:
- R CMD build .
- R CMD check *tar.gz --as-cran

after_script:
- cat /home/travis/build/carlos-alberto-silva/rGEDI/rGEDI.Rcheck/00check.log
- cat /home/travis/build/carlos-alberto-silva/rGEDI/rGEDI.Rcheck/00install.out
